# Generated by Django 4.0.6 on 2022-07-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(max_length=10)),
                ('emp_last_name', models.CharField(max_length=10)),
                ('emp_addr', models.CharField(default='del', max_length=50)),
                ('emp_id', models.CharField(max_length=5)),
            ],
        ),
    ]
