apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django-web-app
  ports:
    - port: 80 #service port
      targetPort: 8000  #container port-computerport
      nodePort: 31000  #to give our own port no.